# Generated by Django 3.2.9 on 2023-01-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QrCod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=False, help_text='Действителен ли сертификат')),
                ('valid_date', models.DateField(blank=True, help_text='Дата окончания действия сертификата', null=True)),
                ('pay_date', models.DateField(blank=True, help_text='Дата оплаты', null=True)),
                ('qr_serial', models.CharField(blank=True, help_text='serial QR', max_length=30, null=True)),
                ('qr_hash', models.CharField(blank=True, help_text='Хэш для QR кода', max_length=30, null=True)),
            ],
        ),
    ]
