# Generated by Django 3.2.9 on 2023-01-12 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Peers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_key', models.CharField(blank=True, help_text='private_key', max_length=30, null=True)),
                ('ip', models.CharField(blank=True, help_text='ip addres', max_length=30, null=True)),
                ('ip_external', models.CharField(blank=True, help_text='ip addres', max_length=30, null=True)),
                ('pub_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
